<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $permission = [
            ['name' => 'user'],
            ['name' => 'user.staff_view'],
            ['name' => 'user.staff_update'],
            ['name' => 'user.staff_delete'],
            ['name' => 'user.staff_create'],
            ['name' => 'user.customer_view'],
            ['name' => 'user.customer_update'],
            ['name' => 'user.customer_delete'],
            ['name' => 'user.customer_create'],
            ['name' => 'user.organization_view'],
            ['name' => 'user.organization_create'],
            ['name' => 'user.organization_update'],
            ['name' => 'user.organization_delete'],
            ['name' => 'role'],
            ['name' => 'role.role_view'],
            ['name' => 'role.role_create'],
            ['name' => 'role.role_update'],
            ['name' => 'role.role_delete'],
            ['name' => 'role.permission_view'],
            ['name' => 'role.permission_create'],
            ['name' => 'role.permission_update'],
            ['name' => 'role.permission_delete'],
            ['name' => 'product'],
            ['name' => 'product.product_view'],
            ['name' => 'product.product_create'],
            ['name' => 'product.product_update'],
            ['name' => 'product.product_delete'],
            ['name' => 'product.category_view'],
            ['name' => 'product.category_create'],
            ['name' => 'product.category_update'],
            ['name' => 'product.category_delete'],
            ['name' => 'product.brand_view'],
            ['name' => 'product.brand_create'],
            ['name' => 'product.brand_update'],
            ['name' => 'product.brand_delete'],
            ['name' => 'product.unit_view'],
            ['name' => 'product.unit_create'],
            ['name' => 'product.unit_update'],
            ['name' => 'product.unit_delete'],
            ['name' => 'product.product-review_view'],
            ['name' => 'product.product-review_delete'],
            ['name' => 'product.attribute_view'],
            ['name' => 'product.attribute_create'],
            ['name' => 'product.attribute_update'],
            ['name' => 'product.attribute_delete'],
            ['name' => 'transaction'],
            ['name' => 'transaction.rfq_view'],
            ['name' => 'transaction.rfq_create'],
            ['name' => 'transaction.rfq_update'],
            ['name' => 'transaction.rfq_delete'],
            ['name' => 'transaction.quotation_view'],
            ['name' => 'transaction.quotation_create'],
            ['name' => 'transaction.quotation_update'],
            ['name' => 'transaction.quotation_delete'],
            ['name' => 'transaction.purchase-order_view'],
            ['name' => 'transaction.purchase-order_create'],
            ['name' => 'transaction.purchase-order_update'],
            ['name' => 'transaction.purchase-order_delete'],
            ['name' => 'shipping'],
            ['name' => 'shipping.shipping-order_view'],
            ['name' => 'shipping.shipping-order_create'],
            ['name' => 'shipping.shipping-order_update'],
            ['name' => 'shipping.shipping-order_delete'],
            ['name' => 'shipping.rates_view'],
            ['name' => 'shipping.rates_create'],
            ['name' => 'shipping.rates_update'],
            ['name' => 'shipping.rates_delete'],
            ['name' => 'shipping.shipping-method_view'],
            ['name' => 'shipping.shipping-method_create'],
            ['name' => 'shipping.shipping-method_update'],
            ['name' => 'shipping.shipping-method_delete'],
            ['name' => 'marketing'],
            ['name' => 'marketing.flash-deals_view'],
            ['name' => 'marketing.flash-deals_create'],
            ['name' => 'marketing.flash-deals_update'],
            ['name' => 'marketing.flash-deals_delete'],
            ['name' => 'marketing.coupon_view'],
            ['name' => 'marketing.coupon_create'],
            ['name' => 'marketing.coupon_update'],
            ['name' => 'marketing.coupon_delete'],
            ['name' => 'marketing.banner_view'],
            ['name' => 'marketing.banner_create'],
            ['name' => 'marketing.banner_update'],
            ['name' => 'marketing.banner_delete'],
            ['name' => 'payment'],
            ['name' => 'payment.payment-method_view'],
            ['name' => 'payment.payment-method_create'],
            ['name' => 'payment.payment-method_update'],
            ['name' => 'payment.payment-method_delete'],
            ['name' => 'payment.payment-history_view'],
            ['name' => 'payment.payment-history_create'],
            ['name' => 'payment.payment-history_update'],
            ['name' => 'payment.payment-history_delete'],
            ['name' => 'merchant'],
            ['name' => 'merchant.merchant_view'],
            ['name' => 'merchant.merchant_create'],
            ['name' => 'merchant.merchant_update'],
            ['name' => 'merchant.merchant_delete'],
            ['name' => 'invoice'],
            ['name' => 'invoice.invoice_view'],
            ['name' => 'audit'],
            ['name' => 'audit.audit_view'],
            ['name' => 'audit.audit_update'],
            ['name' => 'audit.audit_delete'],
            ['name' => 'frontend'],
            ['name' => 'frontend.frontend_create'],
            ['name' => 'frontend.frontend_view'],
            ['name' => 'frontend.frontend_update'],
            ['name' => 'frontend.frontend_delete'],
            ['name' => 'setting'],
            ['name' => 'setting.general-setting_view'],
            ['name' => 'setting.general-setting_update'],
            ['name' => 'setting.vat_view'],
            ['name' => 'setting.vat_create'],
            ['name' => 'setting.vat_update'],
            ['name' => 'setting.vat_delete'],
            ['name' => 'setting.homepage-seo_view'],
            ['name' => 'setting.company-information_view'],
            ['name' => 'dashboard'],
            ['name' => 'dashboard.dashboard_view'],
        ];
        foreach($permission as $rows) {
            $rows['guard_name'] = 'web';
            Permission::create($rows);
        }
    }
}
